name: LaunchDarkly Flag Evaluation

on:
  push:
    branches:
      - main

jobs:
  evaluate_flag:
    name: Evaluate LaunchDarkly Flag
    runs-on: ubuntu-latest

    outputs:
      flag_status: ${{ steps.evaluate.outputs.flag_status }}

    steps:
      - name: Evaluate LaunchDarkly Flag
        id: evaluate
        uses: launchdarkly/gha-flags@main
        with:
          sdk-key: ${{ secrets.sdk-79037d1d-f7c5-4380-ba2a-9f0611717500 }}

          flags: |
            Status_Flag


