name: Update Feature Flag Status

on:
  push:
    branches:
      - main

jobs:
  update-feature-flag-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install LaunchDarkly SDK
        run: |
          pip install launchdarkly-server-sdk

      - name: Fetch feature flag status
        id: fetch-flag-status
        run: |
          FLAG_STATUS=$(python Feature_Flags_3/fetch_feature_flag_status.py | jq -r '.flag_value')
          echo "::set-env name=FLAG_STATUS::$FLAG_STATUS"

      - name: Send status to webhook
        run: |
          curl -X POST -d "{\"flag_status\": \"$FLAG_STATUS\"}" https://webhook.site/f4c87884-959d-4198-81b0-6566980e2138




