name: Check Feature Flag Status

on:
  push:
    branches:
      - main

jobs:
  check_feature_flag_status:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Feature Flag Status
        run: |
          FLAG_STATUS=$(curl -s -H "Authorization: sdk-79037d1d-f7c5-4380-ba2a-9f0611717500" \
                          "https://app.launchdarkly.com/api/v2/flags/default/Status_Flag")
          if [ "$FLAG_STATUS" == "null" ]; then
            echo "Error: Feature flag status is null. Please check your API key, project key, and flag key."
            exit 1
          fi
          FLAG_ENABLED=$(echo $FLAG_STATUS | jq -r '.enabled')
          echo "Feature Flag Status: $FLAG_ENABLED"

