name: Update Feature Flag Status

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [flag_updated]  # Listen for webhook events from LaunchDarkly

jobs:
  update-feature-flag-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install LaunchDarkly SDK
        run: |
          pip install launchdarkly-server-sdk

      - name: Evaluate LaunchDarkly flags
        id: ld
        uses: launchdarkly/gha-flags@v1.0.1
        with:
          sdk-key: ${{ secrets.LAUNCHDARKLY_SDK_KEY }}
          flags: Status_Flag,false

      - name: If true
        if: fromJSON(steps.ld.outputs.Status_Flag) == true
        run: echo "The 'Status_Flag' feature flag is true"

      - name: If false
        if: fromJSON(steps.ld.outputs.Status_Flag) == false
        run: echo "The 'Status_Flag' feature flag is false"

  handle-webhook-event:
    runs-on: ubuntu-latest
    if: github.event_name == 'repository_dispatch'

    steps:
      - name: Extract flag status from webhook payload
        id: extract-flag-status
        run: echo "::set-env name=FLAG_STATUS::${{ github.event.client_payload.flag_value }}"
        shell: bash
      
      - name: Send status to webhook
        run: |
          curl -X POST -d "{\"flag_status\": \"$FLAG_STATUS\"}" https://webhook.site/f4c87884-959d-4198-81b0-6566980e2138
